author: Ethan Xu
title: ew-blog
description: >- 
  Push several information-diversed post
baseurl: "/egg-log"
profile_url: "http://egg-west.github.io"
github_username:  egg-west

markdown: kramdown
theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed


exclude:
  - Gemfile
  - Gemfile.lock

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
