title: Lil'Log
name: "Lilian's Tech Blog"
author: Lilian Weng
twitter_username: lilianweng
baseurl: "/egg-blog"
description: Document my learning notes.
profile_url: "http://egg-west.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
